Fixes the scriptInput method and the signature
bcoin-org/bcoin-org.github.io pull request #193
Opened 2021-10-09 21:47 UTC by ottosch

The guide had some errors:
* The scriptInput method was using the script from the coin object instead of the lockingScript from the keyring.
* Locktime was being set after the call to signInput; hence the signature would always fail. Fixed.
* Not an error, but signInput was using a global wredeem variable (which could be local) declared in scriptInput. I converted the variable into a const and made signInput use the already existing redeem const.
* In Live CLTV section, I added a note about coin maturity. It took me a while to figure out why bcoin was saying my balance was zero after I had mined some blocks.
* Also fixed typo and clarified some few parts.

2021-10-25 20:58 UTC, pinheadmz requested changes
Thanks @ottosch ! Sorry it took me so long to review. Your changes look right, I didn't have time to run through the entire guide myself but I will give it a try this week ;-) I had a question about one of your changes but otherewise thank you for contributing!

2021-10-25 20:58 UTC, pinheadmz commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Isn't `wsh` undefined here, now? Looking at keyring.js `getRedeem()` I think the original syntax is correct -- it's a weird function because the redeem script isn't stored in the coin we are spending. That coin just has a hash of a script. But then what `KeyRing.getRedeem()` does (AFAICT) is check its own script property against the hash we pass in.

If you want to skip this check you can (since this is all a self-contained demo anyway) but then I think you need to replace `getRedeem(wsh)` with `getProgram()`

2021-10-25 20:58 UTC, pinheadmz commented on guides-markdown/cltv.md
> +      redeem,
yes, nice catch

2021-10-25 20:58 UTC, pinheadmz commented on guides-markdown/cltv.md
> +mtx = signInput(mtx, 0, coin, keyring);
Absolutely yes! Obviously we need to set the locktime before we sign

2021-10-25 20:58 UTC, pinheadmz commented on guides-markdown/cltv.md
> +      mtx = scriptInput(mtx, index, ring);
Relates to my first comment, I think it's ok to keep the coin argument here.

2021-10-25 21:10 UTC, pinheadmz commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Ok I just ran through the guide with live bcoin node in regtest and the TX fails to verify with `WITNESS_PROGRAM_MISMATCH` without the steps the original author had (getting prev from coin to be spent, etc).

2021-10-25 21:12 UTC, pinheadmz commented
I compiled all the script snippets from the guide into a single executable script: https://gist.github.com/pinheadmz/3a77c6c713311e394b3e828771342049

Start `bcoin --network=regtest --coinbase-address=<something from your primary wallet>`

...then run the script. It SHOULD fail the first time you run it, after broadcasting the TX. Then I had to manually generate 10 blocks to expire the timelock and run it again:

Here was my output:

```
$ node ~/Desktop/misc-scripts/cltv-test.js
undefined
Success!
Tx:  {
  hash: '414e700774cf1c10349c99e2d8a630d4274381516bf33dab26bc290474c22442',
  witnessHash: '387ece81364364bc6e1b98d0a90c7cd19f4747588aba25a1b555d4637f1ab4ac',
  size: 222,
  virtualSize: 117,
  value: '0.499985',
  fee: '0.0',
  rate: '0.0',
  minFee: '0.00000117',
  height: -1,
  block: null,
  time: 0,
  date: null,
  index: -1,
  version: 1,
  inputs: [
    {
      type: 'witnessscripthash',
      subtype: 'nonstandard',
      address: <Address: type=witness version=0 str=bcrt1qy4ux5c2sr9xw0xquhs9zk9kt5dfqg84mcfwl58785sa9gfpwdf4s8g7rs3>,
      script: <Script: >,
      witness: <Witness: 3044022065a369049c37786ce26d6de620f8703588317f6476b4027e6b0913adce15234402205b9eb99e7c018746bc660e162970532df4f9c81d74a770f2cf7b2b404d6074f101 032a03fa5a43247c13c2ee0a198dcadd82bbdb9ba202cd5f276dd0f430049530b2 02b501b17576a9140b4243ccad4817e1c3112a9be569412f2dbd69cc88ac>,
      redeem: <Script: 437 OP_CHECKLOCKTIMEVERIFY OP_DROP OP_DUP OP_HASH160 0x14 0x0b4243ccad4817e1c3112a9be569412f2dbd69cc OP_EQUALVERIFY OP_CHECKSIG>,
      sequence: 4294967294,
      prevout: <Outpoint: dc4e4fbf2b1ca2e9691e595736be61174610240b3a244b885ce9f9383ca4e950/0>,
      coin: null
    }
  ],
  outputs: [
    {
      type: 'witnesspubkeyhash',
      value: '0.499985',
      script: <Script: OP_0 0x14 0xbfad7b0a5393cf8492c64c3f3b88cf19e88e1e9e>,
      address: <Address: type=witness version=0 str=bcrt1qh7khkzjnj08cfykxfslnhzx0r85gu857p0xxr4>
    }
  ],
  locktime: 437
}
```

2021-10-25 21:53 UTC, ottosch commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Hey, @pinheadmz! I think I screwed up when merging. It should be `const wredeem = ring.script;` instead. The script  was added to the keyring up there (that was in the original guide).  
Is it ok that way?

2021-10-25 23:33 UTC, pinheadmz commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Oh I see yah that would work. Hmmm, my feeling is still to revert it since this is already how `MTX.scriptInput()` works.

2021-10-26 01:02 UTC, ottosch commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
No problem. So, I should keep `coin` as argument and get `wredeem` from `coin`, as it was done before. Any other remarks? If that's all, I will update the code :)

2021-10-26 13:17 UTC, pinheadmz commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Thats it! thank you.

2021-10-26 15:11 UTC, ottosch commented on guides-markdown/cltv.md
> +  const wredeem = ring.getRedeem(wsh);
Done. Thanks a lot!

2021-10-27 17:50 UTC, merged

2021-10-27 17:51 UTC, pinheadmz commented
Great catch Otto, great job thank you!